---
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-c-nginx
  labels:
    app: service-c
data:
  nginx.conf: |
    events {}

    http {
      real_ip_header X-Forwarded-For;

      server {
        listen 80;

        location / {
          add_header Content-Type text/plain;
          return 200 'this is ${OKTETO_NAMESPACE}/service-c\n';
        }
      }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-c
  labels:
    app: service-c
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-c
  template:
    metadata:
      labels:
        app: service-c
    spec:
      containers:
      - name: main
        image: nginx:1.17.6
        volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
      volumes:
        - name: nginx-config
          configMap:
            name: service-c-nginx

---
apiVersion: v1
kind: Service
metadata:
  name: service-c
  labels:
    app: service-c
spec:
  type: ClusterIP
  ports:
  - name: service-c-http
    port: 80
    targetPort: 80
  selector:
    app: service-c

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  labels:
    app: service-c
  name: service-c
spec:
  gateways:
    - mesh
    - ingress-http
  hosts:
    - service-c.${OKTETO_NAMESPACE}.svc.cluster.local
    - service-c-${OKTETO_NAMESPACE}.${OKTETO_DOMAIN}
    - service-c.staging
  http:
    - match:
      - gateways:
          - mesh
        port: 80
      name: mesh-to-mesh
      route:
        - destination:
            host: service-c.${OKTETO_NAMESPACE}.svc.cluster.local
            port:
              number: 80
            subset: stable
          weight: 100
      timeout: 60s
    - name: ingress-gateway-http-app-service
      match:
      - gateways:
          - ingress-http
        port: 80
      route:
        - destination:
            host: service-c.${OKTETO_NAMESPACE}.svc.cluster.local
            port:
              number: 80
            subset: stable
          weight: 100

---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  labels:
    app: service-c
  name: service-c
spec:
  host: service-c
  subsets:
    - labels:
        app: service-c
      name: stable
  trafficPolicy:
    connectionPool:
      tcp:
        connectTimeout: 20s
        maxConnections: 1024
        tcpKeepalive:
          interval: 75s
          time: 7200s
    outlierDetection:
      baseEjectionTime: 5s
      consecutive5xxErrors: 100
      interval: 10s
      maxEjectionPercent: 100

---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  labels:
    app: service-c
  name: service-c
spec:
  endpoints:
    - address: 191.168.1.255
  hosts:
    - service-c.staging
  location: MESH_INTERNAL
  ports:
    - name: http-app-service
      number: 80
      protocol: HTTP
  resolution: STATIC
