apiVersion: v1
kind: ConfigMap
metadata:
  name: service-a-nginx
  labels:
    app: service-a
data:
  nginx.conf: |
    events {}

    http {
      real_ip_header X-Forwarded-For;

      server {
        listen 80;

        location / {
          add_header Content-Type text/plain;
          return 200 'this is service-a\n';
        }

        location /call-b {
          proxy_http_version 1.1;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_pass http://service-b.staging;
        }

        location /call-c {
          proxy_http_version 1.1;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_pass http://service-c.staging;
        }
      }
    }
