---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ingress-http
spec:
  selector:
    istio: ingress
  servers:
    - hosts:
        - '*'
      port:
        name: http
        number: 80
        protocol: HTTP

---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
spec:
  mtls:
    mode: STRICT
