apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: istio-ingress
spec:
  ingressClassName: okteto-controlplane-nginx
  tls:
  - hosts:
      - '*.${OKTETO_DOMAIN}'
  rules:
  - host: '*.${OKTETO_DOMAIN}'
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: istio-ingress
            port:
              number: 80
