apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: istio-ingress
spec:
  ingressClassName: okteto-nginx
  tls:
  - hosts:
      - '*.pablo.dev.okteto.net'
  rules:
  - host: '*.pablo.dev.okteto.net'
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: istio-ingress
            port:
              number: 80
